# Generated by Django 4.0.3 on 2022-08-05 13:52

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='temp_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
