# Generated by Django 4.0.3 on 2022-08-05 14:08

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_phone_number_customer_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='staff_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='verified_phonenumber',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
