# Generated by Django 4.0.3 on 2022-07-31 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_managers_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='staff_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
