# Generated by Django 4.0.3 on 2022-08-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_phone_number_customer_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='staff_id',
        ),
    ]
