# Generated by Django 4.0.3 on 2022-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customer_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
