# Generated by Django 4.0.6 on 2022-07-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='verified_phonenumber',
            field=models.BooleanField(default=False),
        ),
    ]
