# Generated by Django 4.0.3 on 2022-08-05 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
