# Generated by Django 4.0.3 on 2022-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customer_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='temp_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uid',
        ),
        migrations.AddField(
            model_name='customer',
            name='staff_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
