# Generated by Django 4.0.6 on 2022-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='staff_id_no',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='verified_phonenumber',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
