# Generated by Django 4.0.6 on 2022-07-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='date_to',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='date_from',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='date',
        ),
    ]
