# Generated by Django 4.0.6 on 2022-08-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_agent_booking_remove_tour_date_remove_tour_date_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='individuals',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_persons_on_tour',
            field=models.IntegerField(null=True),
        ),
    ]
