# Generated by Django 4.0.6 on 2022-08-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_booking_individuals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_persons_on_tour',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
