# Generated by Django 4.0.6 on 2022-07-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_agent_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_description',
            field=models.TextField(blank=True),
        ),
    ]
