# Generated by Django 4.0.6 on 2022-08-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_booking_no_of_persons_on_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_persons_on_tour',
            new_name='individuals',
        ),
    ]
