# Generated by Django 4.0.6 on 2022-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_package_price_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price_description',
        ),
        migrations.AddField(
            model_name='package',
            name='accomondation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='airport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='feeding',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='flght',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_tour',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='take_off_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='take_off_time',
            field=models.DateTimeField(null=True),
        ),
    ]
