# Generated by Django 4.0.6 on 2022-08-04 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0005_rename_no_of_persons_on_tour_booking_individuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('R', 'Regular'), ('V', 'VIP'), ('VV', 'VVIP')], default='R', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tours.package'),
        ),
    ]
