# Generated by Django 4.0.6 on 2022-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_package_price_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='flght',
            new_name='flight',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
