# Generated by Django 4.0.3 on 2022-07-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'single'), ('C', 'couple'), ('M', 'multiple')], max_length=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.agent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.package')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visa/y/%m/%d/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='passport/y/%m/%d/')),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.booking')),
            ],
        ),
    ]
