# Generated by Django 4.0.6 on 2022-08-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_adminreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminreg',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='adminreg',
            name='birthday_dayofyear_internal',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='approved_by',
        ),
    ]
