# Generated by Django 4.0.3 on 2022-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_booking_visa_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
