# Generated by Django 4.0.6 on 2022-08-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_adminreg_staff_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='password2',
            field=models.CharField(max_length=200),
        ),
    ]
