# Generated by Django 4.0.6 on 2022-08-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_adminreg_password_alter_adminreg_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='staff_no',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
