# Generated by Django 4.0.3 on 2022-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_booking_created_at_booking_customer_booking_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='individuals',
            field=models.IntegerField(choices=[('3', 3), ('4', 4), ('5', 5)], null=True),
        ),
    ]
