# Generated by Django 4.0.3 on 2022-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_booking_individuals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='Booking',
            new_name='booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='individuals',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='image',
            field=models.ImageField(upload_to='passport/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='image',
            field=models.ImageField(upload_to='visa/%y/%m/%d/'),
        ),
    ]
