# Generated by Django 4.0.6 on 2022-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_booking_payment_reference_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
