# Generated by Django 4.0.6 on 2022-07-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_package_price_currency_alter_package_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='image',
            new_name='visa_image',
        ),
    ]
