# Generated by Django 4.0.6 on 2022-07-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_flght_package_flight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='guides/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.agent')),
            ],
        ),
    ]
